services:
  plex:
    image: ghcr.io/0xemma/iventoy-docker:1.0.03
    container_name: iventoy
    restart: always
    privileged: true
    ports:
      - 26000:26000
    volumes:
      - /PATH/TO/ISOS:/iventoy/iso
